spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/haggler
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8080
#  servlet:
#    context-path: /ecommerce